/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Csv Api */
        post: operations["import_csv_api_api_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description アプリとDBの両方が利用可能か確認する。
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertRow */
        AlertRow: {
            /** Campaign */
            campaign: string;
            /** Type */
            type: string;
            /** Message */
            message: string;
            /** Previous Value */
            previous_value: string;
            /** Current Value */
            current_value: string;
            /** Unit */
            unit: string;
        };
        /** Body_import_csv_api_api_imports_post */
        Body_import_csv_api_api_imports_post: {
            /** Csv File */
            csv_file: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportErrorResponse */
        ImportErrorResponse: {
            /**
             * Status
             * @constant
             */
            status: "error";
            /** Message */
            message: string;
            /** Validation Errors */
            validation_errors?: string[] | null;
        };
        /** ImportSuccessResponse */
        ImportSuccessResponse: {
            /**
             * Status
             * @constant
             */
            status: "success";
            /** Analysis Id */
            analysis_id: number;
            /** File Name */
            file_name: string;
            /** Row Count */
            row_count: number;
            /** Summary */
            summary: components["schemas"]["SummaryRow"][];
            /** Alerts */
            alerts: components["schemas"]["AlertRow"][];
            /** Ai Report */
            ai_report?: string | null;
        };
        /** SummaryRow */
        SummaryRow: {
            /** Campaign */
            campaign: string;
            /** Impressions */
            impressions: number;
            /** Clicks */
            clicks: number;
            /** Cost */
            cost: number;
            /** Conversions */
            conversions: number;
            /** Revenue */
            revenue: number;
            /** Ctr */
            ctr: number | null;
            /** Cpa */
            cpa: number | null;
            /** Roas */
            roas: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    import_csv_api_api_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_csv_api_api_imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportSuccessResponse"] | components["schemas"]["ImportErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
